# SPDX-FileCopyrightText: 2025 Wybren Koelmans (uBdead) <wybrenkoelmans@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: REUSE Compliance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run REUSE lint via Docker
        run: |
          docker run --rm -v "$PWD:/data" fsfe/reuse lint
